language: java
sudo: false # faster builds
jdk:
  - oraclejdk8
script: "mvn clean install"
after_success:
  - bash <(curl -s https://codecov.io/bash)
#  cache:
#    directories:
#    - $HOME/.m2â‰ˆ
#notifications:
#    email: