spring:
  profiles: prod
  datasource:
      driverClassName: org.postgresql.Driver
      url: ${DATABASE_JDBC_URL}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
  thymeleaf:
    cache: true
logging:
    config: classpath:logback-tomcat.xml