spring:
  profiles: dev
  datasource:
      driverClassName: org.postgresql.Driver
      url: ${DATABASE_JDBC_URL}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
  thymeleaf:
    cache: false